In [7]:
import numpy as np
import time

a = np.array([1,2,3,4,5,6])
a = np.reshape(a,(3,2)).T
print(a)
a = np.reshape(a, (1,6))
a = np.squeeze(a)
print(a)

[[1 3 5]
 [2 4 6]]
[1 3 5 2 4 6]


In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.random.seed=1
np.random.randn(2,2)

array([[0.39273444, 0.06790473],
       [0.07132092, 0.40051546]])